[build]
  command = "npm install && npx turbo run build --filter=school-portal"
  publish = "apps/school-portal/.next"
  
[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXTAUTH_SECRET = "your-production-secret-here-replace-this"
  NEXTAUTH_URL = "https://your-site-name.netlify.app"

# Use Essential Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"