[build]
  command = "cd ../.. && npm install && npx turbo run build --filter=main-website"
  publish = "apps/main-website/.next"
  
[build.environment]
  NODE_VERSION = "18"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"