version: '3.8'

services:
  moodle:
    image: bitnami/moodle:latest
    container_name: capas-moodle
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=capas_moodle
      - MOODLE_DATABASE_USER=capas_user
      - MOODLE_DATABASE_PASSWORD=capas_secure_password
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=CAPASAdmin2024!
      - MOODLE_EMAIL=admin@capas.edu.bs
      - MOODLE_SITE_NAME=CAPAS Learning Management System
      - MOODLE_SKIP_BOOTSTRAP=no
      - PHP_MEMORY_LIMIT=256M
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb
    networks:
      - capas-network

  mariadb:
    image: bitnami/mariadb:latest
    container_name: capas-mariadb
    environment:
      - MARIADB_USER=capas_user
      - MARIADB_PASSWORD=capas_secure_password
      - MARIADB_DATABASE=capas_moodle
      - MARIADB_ROOT_PASSWORD=root_secure_password
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - capas-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: capas-phpmyadmin
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root_secure_password
    depends_on:
      - mariadb
    networks:
      - capas-network

volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  mariadb_data:
    driver: local

networks:
  capas-network:
    driver: bridge